stages:
  - lint
  - deploy

ruff:
  image:
    name: python:3.9-slim-bookworm
    entrypoint: [ "/usr/bin/env" ]
  stage: lint
  before_script:
  - pip install poetry
  - poetry install
  - source "$(poetry env info --path)/bin/activate" || exit 1
  script:
    - ruff check .

mirror_to_github:
  stage: deploy
  image: docker
  variables:
    GIT_STRATEGY: clone
  only:
    - main
  script:
    - apk add --no-cache git
    - cd $CI_PROJECT_DIR  # Navigate to the project directory
    - git checkout main
    - git config user.email "sentinel@inesctec.pt"
    - git config user.name "cpes-sentinel"
    - git reset $(git commit-tree HEAD^{tree} -m "Upload repository mirror")
    - git add -A
    - git remote add github https://github.com/CPES-Power-and-Energy-Systems/tsg-client
    - git push --force
      "https://oauth2:${GITHUB_TOKEN}@github.com/CPES-Power-and-Energy-Systems/tsg-client.git"
      main