stages:
  - lint
  - test
  - deploy

ruff:
  image:
    name: python:3.9-slim-bookworm
    entrypoint: [ "/usr/bin/env" ]
  stage: lint
  before_script:
  - pip install poetry
  - poetry install
  - source "$(poetry env info --path)/bin/activate" || exit 1
  script:
    - ruff check .

unit_tests:
  image:
    name: python:3.9-slim-bookworm
    entrypoint: [ "/usr/bin/env" ]
  stage: test
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry run pytest unittests/

mirror_to_github:
  stage: deploy
  image: docker
  variables:
    GIT_STRATEGY: clone
  only:
    - main
  script:
    - apk add --no-cache git
    - cd $CI_PROJECT_DIR  # Navigate to the project directory
    - git checkout main
    - LAST_COMMIT_MSG=$(git log --format=%B -n 1)
    - LAST_COMMIT_NAME=$(git log -1 --pretty=format:'%an')
    - LAST_COMMIT_EMAIL=$(git log -1 --pretty=format:'%ae')
    
    - git clone https://oauth2:${GITHUB_TOKEN}@github.com/CPES-Power-and-Energy-Systems/tsg-client.git github
    - rm -rf .git
    - mv github/.git .git
    - rm -rf github
    - git add -A
    - git config user.email "$LAST_COMMIT_EMAIL"
    - git config user.name "$LAST_COMMIT_NAME"
    - git commit -m "$LAST_COMMIT_MSG"
    - git push